---
# tasks file for firewalld
# install ssh packages
- name: Check if firewalld package is installed (on RHEL).
  command: yum list installed firewalld
  args:
    warn: false
  register: firewalld_installed
  ignore_errors: true
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
#    - firewall_disable_firewalld
  check_mode: false

- name: Enable firewalld service
  service:
    name: firewalld
    enabled: "{{ firewalld_enabled }}"

- name: permit traffic in default zone for ssh service
  firewalld:
    service: ssh
    permanent: yes
    state: enabled

- name: permit traffic in default zone for http service
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: permit traffic in default zone for https service
  firewalld:
    service: https
    permanent: yes
    state: enabled

- name: Restart firewalld service
  service:
    name: firewalld
    state: restarted